### PR TITLE
docs: move old naxsi wiki to docs directory and comb it up a little

### PR DESCRIPTION
**Pull request by selivan**
Moved old naxsi wiki content to `docs` directory.

Some combing up: fixed links.

Note: a couple of `TODO DOCUMENTATION` labels on new features that should be documented properly.

Later that can be used to make a github.io project page.

### CODE REVIEW

**Comment by wargio** [comment]
That will be very useful!
I'm not a 100% if i want this directly in `main` or to make a branch called `docs` and put it there till i rewrite most of the stuff in there.

**Comment by selivan** [comment]
I would suggest using simple directory inside project, having 2 separate branches with different content feels like unnecessary complication. Or, if you would like to keep .md files outside of code, it can be moved to a separate repository, used as source for https://wargio.github.io/naxsi, github supports that option.

**Comment by wargio** [comment]
i would then merge it into main once polished. there are some very old info in those images etc.. which i want to remove.

**Comment by selivan** [comment]
If you point out which ones, I'll try to fix that.

**Comment by wargio** [comment]
Please add at the end of this [file](https://github.com/wargio/naxsi/blob/main/.reuse/dep5) these lines, so i can merge this.

```

Files: docs/**
Copyright: 2019 nbs-system <security@nbs-system.com>
License: GPL-3.0-or-later
```

**Comment by selivan** [comment]
✅ done

**Review by wargio — APPROVED** [review]

**Comment by wargio** [comment]
Looks like the reuse action got updated and broke. i think is mergiable.

**Pull request merged**
