### PR TITLE
Fix issue nbs-system/naxsi#626

### PR DESCRIPTION
**Pull request by wargio**
Fix https://github.com/nbs-system/naxsi/issues/626

### CODE REVIEW

**Comment by elfring** [comment]
Thanks for your adjustment of affected include guards.

:thinking: How do you think about to rename also the identifier “[`__FILENAME__`](https://github.com/wargio/naxsi/blob/5f73d2b8742e1d904bd6f422c50bac251b4cde13/naxsi_src/naxsi_skeleton.c#L24 "Update candidate")”?

**Comment by wargio** [comment]
that should change too, but is not an issue since is defined in a C file.

**Comment by elfring** [comment]
>…, but is not an issue since is defined in a C file.

Please reconsider this view once more.

**Comment by wargio** [comment]
i will change it for sure. but i do not understand what you are doing with the code.

**Comment by wargio** [comment]
https://github.com/wargio/naxsi/pull/73

**Pull request merged**
