### PR TITLE
Drop libinjection submodule and build with external libinjection

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This is an adaptation of the patch I made for shipping the naxsi module in Fedora.

### CODE REVIEW

**Comment by wargio** [comment]
we could configure it.. i like having a pinned version of libinjection. maybe we could have a check, if available in the system, then use the system one, otherwise the gitmodule?

**Comment by Conan-Kudo** [comment]
Sure, I could rework this to make it additive instead...

**Comment by wargio** [comment]
@Conan-Kudo do you want me to finish this PR?

**Comment by Conan-Kudo** [comment]
Yes please. I'm not going to have time for it anytime soon.

**Pull request closed without merging**
